/**
 * Sarthi Application Version Configuration
 * Represents the version of the currently running frontend bundle.
 * Auto-generated by bump-version.js
 */

export const APP_VERSION = '1.2.116';
export const BUILD_TIME = '2026-09-30T08:29:25.484Z';
export const GIT_COMMIT = '83257231';

export const getActiveAppVersion = () => {
  return APP_VERSION;
};

export const getActiveGitCommit = () => {
  return GIT_COMMIT;
};

export const getActiveBuildTime = () => {
  return BUILD_TIME;
};

export const setAcknowledgedVersion = (version) => {
  try {
    if (version) {
      sessionStorage.setItem('sarthi_acknowledged_version', String(version).trim());
    }
  } catch (e) {
    // Ignore storage issues
  }
};
