/**
 * Sarthi Application Version Configuration
 * Represents the version of the currently running frontend bundle.
 * Auto-generated by bump-version.js
 */

export const APP_VERSION = '1.2.28';
export const BUILD_TIME = '2026-09-07T10:02:50.923Z';
export const GIT_COMMIT = '5b9b320c';

export const getActiveAppVersion = () => {
  return APP_VERSION;
};

export const setAcknowledgedVersion = (version) => {
  try {
    if (version) {
      sessionStorage.setItem('sarthi_acknowledged_version', String(version).trim());
    }
  } catch (e) {
    // Ignore storage issues
  }
};
